apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics

resources:
  - flink-deployment.yaml

commonLabels:
  app.kubernetes.io/name: httproute-realtime-analytics
  app.kubernetes.io/component: flink-job
  app.kubernetes.io/part-of: analytics-platform

configMapGenerator:
  - name: flink-job-config
    literals:
      - nats.url=nats://nats.analytics.svc.cluster.local:4222
      - nats.stream=ENVOY_ACCESS_LOGS
      - nats.subject=envoy.access.logs
      - nessie.uri=http://nessie.analytics.svc.cluster.local:19120/api/v1
      - iceberg.warehouse=s3a://iceberg-warehouse
